server {
	listen 8001 8002;
	host 127.0.0.1;

	root www;
	index index.html;
	error_page 404 www/errors/404.html;
	client_max_body_size 2000000;

	location / {
		autoindex on;
		allow_methods GET POST DELETE;
		root www;
		index index.html;
		upload_dir www/uploads/;
		cgi .php /usr/bin/php;
	}

	location /html {
		index index.html;
		allow_methods GET;
		root www;
	}

	location /images {
		root www;
		allow_methods GET POST DELETE;
		autoindex on;
	}

	location /redirect {
		return https://media.istockphoto.com/id/1318611667/de/video/fliegen-sie-durch-einen-fantastischen-wald-von-tanzenden-neonpilzen-vj-loop-animation.mp4?s=mp4-640x640-is&k=20&c=kQb83H1DSC70kdgBWQgjAZPO8FptdZPDit9ND5qB4YU=;
	}
}

server {
	listen 8003;
	host 127.0.0.1;

	root www;
	index index.html;
	error_page 404 www/errors/404.html;
	client_max_body_size 2000000;

	location / {
		root www;
		allow_methods GET POST;
		autoindex off;
	}

	location /html {
		allow_methods GET;
	}

	location /images {
		root www;
		allow_methods GET POST DELETE;
		autoindex on;
	}
}

server {
	listen 8004;
	host 127.0.0.1;

	root www;
	index index.html;
	error_page 404 www/errors/404.html;
	client_max_body_size 2000000;

	location / {
		autoindex on;
		allow_methods GET POST DELETE;
		root www;
		index index.html;
		upload_dir www/uploads/;
		cgi .php /usr/bin/php;
	}

	location /html {
		allow_methods GET;
	}

	location /images {
		root www;
		allow_methods GET POST DELETE;
		autoindex on;
	}
}